export type TitlePhraseLexiconEntry = {
  key: string;
  en: string;
  zh: string;
  count: number;
  source: "dictionary" | "pattern" | "word" | "pending";
  confidence: number;
};

export const TITLE_PHRASE_LEXICON_VERSION = "2026-08-01T16:43:03.426Z";

export const TITLE_PHRASE_LEXICON: TitlePhraseLexiconEntry[] = [
  { key: "baby", en: "baby", zh: "婴儿", count: 73, source: "word", confidence: 0.9 },
  { key: "toddler", en: "toddler", zh: "儿童", count: 55, source: "word", confidence: 0.9 },
  { key: "kids", en: "kids", zh: "儿童", count: 53, source: "dictionary", confidence: 1 },
  { key: "stroller", en: "stroller", zh: "推车", count: 52, source: "dictionary", confidence: 1 },
  { key: "bike", en: "bike", zh: "自行车", count: 41, source: "word", confidence: 0.9 },
  { key: "travel", en: "travel", zh: "旅行", count: 36, source: "dictionary", confidence: 1 },
  { key: "car", en: "car", zh: "车", count: 36, source: "dictionary", confidence: 1 },
  { key: "seat", en: "seat", zh: "座椅", count: 35, source: "dictionary", confidence: 1 },
  { key: "toddlers", en: "toddlers", zh: "儿童", count: 31, source: "dictionary", confidence: 1 },
  { key: "fold", en: "fold", zh: "折叠", count: 30, source: "dictionary", confidence: 1 },
  { key: "infant", en: "infant", zh: "婴儿", count: 29, source: "dictionary", confidence: 1 },
  { key: "compact", en: "compact", zh: "紧凑", count: 28, source: "dictionary", confidence: 1 },
  { key: "lightweight", en: "lightweight", zh: "轻量", count: 26, source: "dictionary", confidence: 1 },
  { key: "wheels", en: "wheels", zh: "轮", count: 26, source: "word", confidence: 0.9 },
  { key: "balance", en: "balance", zh: "平衡", count: 25, source: "dictionary", confidence: 1 },
  { key: "ages", en: "ages", zh: "年龄", count: 25, source: "word", confidence: 0.9 },
  { key: "balance_bike", en: "balance bike", zh: "平衡车", count: 24, source: "dictionary", confidence: 1 },
  { key: "for_kids", en: "for kids", zh: "儿童", count: 24, source: "word", confidence: 0.9 },
  { key: "ride", en: "ride", zh: "骑乘", count: 24, source: "dictionary", confidence: 1 },
  { key: "adjustable", en: "adjustable", zh: "可调节", count: 23, source: "dictionary", confidence: 1 },
  { key: "year", en: "year", zh: "岁", count: 23, source: "word", confidence: 0.9 },
  { key: "black", en: "black", zh: "黑色", count: 22, source: "word", confidence: 0.9 },
  { key: "for_toddlers", en: "for toddlers", zh: "儿童", count: 21, source: "word", confidence: 0.9 },
  { key: "years", en: "years", zh: "岁", count: 21, source: "word", confidence: 0.9 },
  { key: "toy", en: "toy", zh: "玩具", count: 21, source: "word", confidence: 0.9 },
  { key: "year_old", en: "year old", zh: "岁", count: 20, source: "word", confidence: 0.9 },
  { key: "ride_on", en: "ride on", zh: "骑乘", count: 20, source: "dictionary", confidence: 1 },
  { key: "canopy", en: "canopy", zh: "顶篷", count: 20, source: "dictionary", confidence: 1 },
  { key: "stroller_with", en: "stroller with", zh: "推车", count: 19, source: "word", confidence: 0.9 },
  { key: "girls", en: "girls", zh: "女孩", count: 19, source: "word", confidence: 0.9 },
  { key: "bike_for", en: "bike for", zh: "自行车", count: 18, source: "word", confidence: 0.9 },
  { key: "car_seat", en: "car seat", zh: "安全座椅", count: 18, source: "dictionary", confidence: 1 },
  { key: "boys", en: "boys", zh: "男孩", count: 18, source: "word", confidence: 0.9 },
  { key: "toys", en: "toys", zh: "玩具", count: 18, source: "word", confidence: 0.9 },
  { key: "lbs", en: "lbs", zh: "磅", count: 17, source: "dictionary", confidence: 1 },
  { key: "baby_balance_bike", en: "baby balance bike", zh: "婴儿平衡自行车", count: 16, source: "word", confidence: 0.9 },
  { key: "baby_balance", en: "baby balance", zh: "婴儿平衡", count: 16, source: "word", confidence: 0.9 },
  { key: "basket", en: "basket", zh: "篮", count: 15, source: "word", confidence: 0.9 },
  { key: "double", en: "double", zh: "双人", count: 15, source: "dictionary", confidence: 1 },
  { key: "months", en: "months", zh: "个月", count: 15, source: "dictionary", confidence: 1 },
  { key: "push", en: "push", zh: "推行", count: 15, source: "word", confidence: 0.9 },
  { key: "years_old", en: "years old", zh: "岁", count: 14, source: "word", confidence: 0.9 },
  { key: "birthday", en: "birthday", zh: "生日", count: 14, source: "dictionary", confidence: 1 },
  { key: "tricycle", en: "tricycle", zh: "三轮车", count: 14, source: "word", confidence: 0.9 },
  { key: "first", en: "first", zh: "首次", count: 14, source: "dictionary", confidence: 1 },
  { key: "inch", en: "inch", zh: "英寸", count: 14, source: "word", confidence: 0.9 },
  { key: "travel_stroller", en: "travel stroller", zh: "旅行推车", count: 13, source: "dictionary", confidence: 1 },
  { key: "baby_stroller", en: "baby stroller", zh: "婴儿推车", count: 13, source: "dictionary", confidence: 1 },
  { key: "electric", en: "electric", zh: "电动", count: 13, source: "word", confidence: 0.9 },
  { key: "toys_for", en: "toys for", zh: "玩具", count: 13, source: "word", confidence: 0.9 },
  { key: "scooter", en: "scooter", zh: "滑板车", count: 13, source: "word", confidence: 0.9 },
  { key: "storage", en: "storage", zh: "储物", count: 13, source: "word", confidence: 0.9 },
  { key: "graco", en: "graco", zh: "Graco", count: 13, source: "dictionary", confidence: 1 },
  { key: "double_stroller", en: "double stroller", zh: "双人推车", count: 12, source: "dictionary", confidence: 1 },
  { key: "travel_system", en: "travel system", zh: "出行系统", count: 12, source: "dictionary", confidence: 1 },
  { key: "recline", en: "recline", zh: "可躺", count: 12, source: "dictionary", confidence: 1 },
  { key: "system", en: "system", zh: "系统", count: 12, source: "word", confidence: 0.9 },
  { key: "frame", en: "frame", zh: "车架", count: 12, source: "word", confidence: 0.9 },
  { key: "gifts", en: "gifts", zh: "礼物", count: 12, source: "dictionary", confidence: 1 },
  { key: "wagon", en: "wagon", zh: "拖车", count: 12, source: "word", confidence: 0.9 },
  { key: "toddler_balance_bike", en: "toddler balance bike", zh: "儿童平衡车", count: 11, source: "dictionary", confidence: 1 },
  { key: "toddler_balance", en: "toddler balance", zh: "儿童平衡", count: 11, source: "word", confidence: 0.9 },
  { key: "for_1_year_old", en: "for 1 year old", zh: "1岁", count: 11, source: "word", confidence: 0.9 },
  { key: "toddler_bike", en: "toddler bike", zh: "儿童自行车", count: 11, source: "word", confidence: 0.9 },
  { key: "convertible", en: "convertible", zh: "可转换", count: 11, source: "dictionary", confidence: 1 },
  { key: "1_year_old", en: "1 year old", zh: "1岁", count: 11, source: "word", confidence: 0.9 },
  { key: "baby_trend", en: "baby trend", zh: "婴儿trend", count: 11, source: "word", confidence: 0.73 },
  { key: "for_1_year", en: "for 1 year", zh: "1岁", count: 11, source: "word", confidence: 0.9 },
  { key: "infant_car", en: "infant car", zh: "婴儿车", count: 11, source: "word", confidence: 0.9 },
  { key: "foldable", en: "foldable", zh: "可折叠", count: 11, source: "dictionary", confidence: 1 },
  { key: "1_year", en: "1 year", zh: "1岁", count: 11, source: "word", confidence: 0.9 },
  { key: "for_1", en: "for 1", zh: "1", count: 11, source: "word", confidence: 0.9 },
  { key: "trend", en: "trend", zh: "Trend", count: 11, source: "dictionary", confidence: 1 },
  { key: "infant_car_seat", en: "infant car seat", zh: "婴儿安全座椅", count: 10, source: "dictionary", confidence: 1 },
  { key: "ride_on_toy", en: "ride on toy", zh: "骑乘玩具", count: 10, source: "dictionary", confidence: 1 },
  { key: "boys_girls", en: "boys girls", zh: "男孩女孩", count: 10, source: "dictionary", confidence: 1 },
  { key: "bike_with", en: "bike with", zh: "自行车", count: 10, source: "word", confidence: 0.9 },
  { key: "colorful", en: "colorful", zh: "炫彩", count: 10, source: "dictionary", confidence: 1 },
  { key: "for_ages", en: "for ages", zh: "年龄", count: 10, source: "word", confidence: 0.9 },
  { key: "training", en: "training", zh: "辅助", count: 10, source: "word", confidence: 0.9 },
  { key: "bicycle", en: "bicycle", zh: "自行车", count: 10, source: "dictionary", confidence: 1 },
  { key: "control", en: "control", zh: "控制", count: 10, source: "word", confidence: 0.9 },
  { key: "outdoor", en: "outdoor", zh: "户外", count: 10, source: "word", confidence: 0.9 },
  { key: "safety", en: "safety", zh: "安全", count: 10, source: "word", confidence: 0.9 },
  { key: "easy", en: "easy", zh: "便捷", count: 10, source: "dictionary", confidence: 1 },
  { key: "colorful_lighting", en: "colorful lighting", zh: "炫彩灯光", count: 9, source: "dictionary", confidence: 1 },
  { key: "compact_fold", en: "compact fold", zh: "紧凑折叠", count: 9, source: "word", confidence: 0.9 },
  { key: "dream_on_me", en: "dream on me", zh: "Dream On Me", count: 9, source: "dictionary", confidence: 1 },
  { key: "kids_ages", en: "kids ages", zh: "儿童年龄", count: 9, source: "word", confidence: 0.9 },
  { key: "kids_bike", en: "kids bike", zh: "儿童自行车", count: 9, source: "dictionary", confidence: 1 },
  { key: "dream_on", en: "dream on", zh: "Dream On", count: 9, source: "dictionary", confidence: 1 },
  { key: "lighting", en: "lighting", zh: "灯光", count: 9, source: "dictionary", confidence: 1 },
  { key: "mompush", en: "mompush", zh: "Mompush", count: 9, source: "dictionary", confidence: 1 },
  { key: "toy_for", en: "toy for", zh: "玩具", count: 9, source: "word", confidence: 0.9 },
  { key: "remote", en: "remote", zh: "遥控", count: 9, source: "word", confidence: 0.9 },
  { key: "dream", en: "dream", zh: "Dream", count: 9, source: "dictionary", confidence: 1 },
  { key: "on_me", en: "on me", zh: "", count: 9, source: "pending", confidence: 0 },
  { key: "blue", en: "blue", zh: "蓝色", count: 9, source: "word", confidence: 0.9 },
  { key: "twin", en: "twin", zh: "双人", count: 9, source: "dictionary", confidence: 1 },
  { key: "umbrella_stroller", en: "umbrella stroller", zh: "伞车", count: 8, source: "dictionary", confidence: 1 },
  { key: "remote_control", en: "remote control", zh: "遥控", count: 8, source: "dictionary", confidence: 1 },
  { key: "for_kids_ages", en: "for kids ages", zh: "儿童年龄", count: 8, source: "word", confidence: 0.9 },
  { key: "stroller_for", en: "stroller for", zh: "推车", count: 8, source: "word", confidence: 0.9 },
  { key: "tricycle_for", en: "tricycle for", zh: "三轮车", count: 8, source: "word", confidence: 0.9 },
  { key: "to_toddler", en: "to toddler", zh: "儿童", count: 8, source: "word", confidence: 0.9 },
  { key: "children", en: "children", zh: "儿童", count: 8, source: "dictionary", confidence: 1 },
  { key: "umbrella", en: "umbrella", zh: "伞车", count: 8, source: "dictionary", confidence: 1 },
  { key: "ride_on", en: "ride-on", zh: "骑乘", count: 8, source: "dictionary", confidence: 1 },
  { key: "carbon", en: "carbon", zh: "碳", count: 8, source: "word", confidence: 0.9 },
  { key: "parent", en: "parent", zh: "家长", count: 8, source: "dictionary", confidence: 1 },
  { key: "chair", en: "chair", zh: "座椅", count: 8, source: "dictionary", confidence: 1 },
  { key: "pedal", en: "pedal", zh: "脚踏", count: 8, source: "dictionary", confidence: 1 },
  { key: "radio", en: "radio", zh: "Radio", count: 8, source: "dictionary", confidence: 1 },
  { key: "girl", en: "girl", zh: "女孩", count: 8, source: "dictionary", confidence: 1 },
  { key: "high", en: "high", zh: "高", count: 8, source: "word", confidence: 0.9 },
  { key: "boy", en: "boy", zh: "男孩", count: 8, source: "dictionary", confidence: 1 },
  { key: "baby_balance_bike_toys", en: "baby balance bike toys", zh: "婴儿平衡自行车玩具", count: 7, source: "word", confidence: 0.9 },
  { key: "balance_bike_toys_for", en: "balance bike toys for", zh: "平衡自行车玩具", count: 7, source: "word", confidence: 0.9 },
  { key: "balance_bike_toys", en: "balance bike toys", zh: "平衡自行车玩具", count: 7, source: "word", confidence: 0.9 },
  { key: "toys_for_1_year", en: "toys for 1 year", zh: "玩具1岁", count: 7, source: "word", confidence: 0.9 },
  { key: "training_wheels", en: "training wheels", zh: "辅助轮", count: 7, source: "dictionary", confidence: 1 },
  { key: "birthday_gifts", en: "birthday gifts", zh: "生日礼物", count: 7, source: "dictionary", confidence: 1 },
  { key: "indoor_outdoor", en: "indoor outdoor", zh: "室内外", count: 7, source: "dictionary", confidence: 1 },
  { key: "storage_basket", en: "storage basket", zh: "置物篮", count: 7, source: "dictionary", confidence: 1 },
  { key: "bike_toys_for", en: "bike toys for", zh: "自行车玩具", count: 7, source: "word", confidence: 0.9 },
  { key: "birthday_gift", en: "birthday gift", zh: "生日礼物", count: 7, source: "dictionary", confidence: 1 },
  { key: "and_toddlers", en: "and toddlers", zh: "儿童", count: 7, source: "word", confidence: 0.9 },
  { key: "and_toddler", en: "and toddler", zh: "儿童", count: 7, source: "word", confidence: 0.9 },
  { key: "baby_travel", en: "baby travel", zh: "婴儿旅行", count: 7, source: "word", confidence: 0.9 },
  { key: "radio_flyer", en: "radio flyer", zh: "Radio Flyer", count: 7, source: "dictionary", confidence: 1 },
  { key: "ride_on_car", en: "ride on car", zh: "骑乘车", count: 7, source: "word", confidence: 0.9 },
  { key: "high_chair", en: "high chair", zh: "高chair", count: 7, source: "word", confidence: 0.73 },
  { key: "toys_for_1", en: "toys for 1", zh: "玩具1", count: 7, source: "word", confidence: 0.9 },
  { key: "bike_toys", en: "bike toys", zh: "自行车玩具", count: 7, source: "word", confidence: 0.9 },
  { key: "inch_kids", en: "inch kids", zh: "英寸儿童", count: 7, source: "word", confidence: 0.9 },
  { key: "wagon_for", en: "wagon for", zh: "拖车", count: 7, source: "word", confidence: 0.9 },
  { key: "no_pedal", en: "no pedal", zh: "无脚踏", count: 7, source: "dictionary", confidence: 1 },
  { key: "one_hand", en: "one-hand", zh: "单手", count: 7, source: "dictionary", confidence: 1 },
  { key: "portable", en: "portable", zh: "便携", count: 7, source: "dictionary", confidence: 1 },
  { key: "seat_and", en: "seat and", zh: "座椅", count: 7, source: "word", confidence: 0.9 },
  { key: "harness", en: "harness", zh: "安全带", count: 7, source: "dictionary", confidence: 1 },
  { key: "on_toys", en: "on toys", zh: "玩具", count: 7, source: "word", confidence: 0.9 },
  { key: "2_in_1", en: "2-in-1", zh: "2 合 1", count: 7, source: "pattern", confidence: 0.9 },
  { key: "indoor", en: "indoor", zh: "室内", count: 7, source: "word", confidence: 0.9 },
  { key: "on_car", en: "on car", zh: "车", count: 7, source: "word", confidence: 0.9 },
  { key: "walker", en: "walker", zh: "学步", count: 7, source: "dictionary", confidence: 1 },
  { key: "12_24", en: "12-24", zh: "12-24 个月", count: 7, source: "dictionary", confidence: 1 },
  { key: "flyer", en: "flyer", zh: "Flyer", count: 7, source: "dictionary", confidence: 1 },
  { key: "green", en: "green", zh: "绿色", count: 7, source: "word", confidence: 0.9 },
  { key: "large", en: "large", zh: "大容量", count: 7, source: "dictionary", confidence: 1 },
  { key: "light", en: "light", zh: "轻便", count: 7, source: "dictionary", confidence: 1 },
  { key: "speed", en: "speed", zh: "速度", count: 7, source: "dictionary", confidence: 1 },
  { key: "grey", en: "grey", zh: "灰色", count: 7, source: "word", confidence: 0.9 },
  { key: "soft", en: "soft", zh: "柔软", count: 7, source: "dictionary", confidence: 1 },
  { key: "1_3", en: "1-3", zh: "1-3 岁", count: 7, source: "dictionary", confidence: 1 },
  { key: "12v", en: "12v", zh: "12V", count: 7, source: "dictionary", confidence: 1 },
  { key: "led", en: "led", zh: "LED", count: 7, source: "dictionary", confidence: 1 },
  { key: "red", en: "red", zh: "红色", count: 7, source: "word", confidence: 0.9 },
  { key: "colorful_lighting_baby_balance", en: "colorful lighting baby balance", zh: "colorfullighting婴儿平衡", count: 6, source: "word", confidence: 0.73 },
  { key: "lighting_baby_balance_bike", en: "lighting baby balance bike", zh: "lighting婴儿平衡自行车", count: 6, source: "word", confidence: 0.81 },
  { key: "month_toddler_balance_bike", en: "month toddler balance bike", zh: "month儿童平衡自行车", count: 6, source: "word", confidence: 0.81 },
  { key: "colorful_lighting_baby", en: "colorful lighting baby", zh: "婴儿炫彩灯光", count: 6, source: "dictionary", confidence: 1 },
  { key: "lighting_baby_balance", en: "lighting baby balance", zh: "lighting婴儿平衡", count: 6, source: "word", confidence: 0.78 },
  { key: "month_toddler_balance", en: "month toddler balance", zh: "month儿童平衡", count: 6, source: "word", confidence: 0.78 },
  { key: "tricycle_for_toddlers", en: "tricycle for toddlers", zh: "三轮车儿童", count: 6, source: "word", confidence: 0.9 },
  { key: "travel_stroller_with", en: "travel stroller with", zh: "旅行推车", count: 6, source: "word", confidence: 0.9 },
  { key: "babies_and_toddlers", en: "babies and toddlers", zh: "babies儿童", count: 6, source: "word", confidence: 0.73 },
  { key: "jogging_stroller", en: "jogging stroller", zh: "慢跑推车", count: 6, source: "dictionary", confidence: 1 },
  { key: "stroller_compact", en: "stroller compact", zh: "推车紧凑", count: 6, source: "word", confidence: 0.9 },
  { key: "toddler_tricycle", en: "toddler tricycle", zh: "儿童三轮车", count: 6, source: "word", confidence: 0.9 },
  { key: "bike_toys_for_1", en: "bike toys for 1", zh: "自行车玩具1", count: 6, source: "word", confidence: 0.9 },
  { key: "lighting_baby", en: "lighting baby", zh: "lighting婴儿", count: 6, source: "word", confidence: 0.73 },
  { key: "month_toddler", en: "month toddler", zh: "month儿童", count: 6, source: "word", confidence: 0.73 },
  { key: "upf_50_canopy", en: "upf 50 canopy", zh: "upf50顶篷", count: 6, source: "word", confidence: 0.78 },
  { key: "ride_on_toys", en: "ride on toys", zh: "骑乘玩具", count: 6, source: "word", confidence: 0.9 },
  { key: "year_old_boy", en: "year old boy", zh: "岁boy", count: 6, source: "word", confidence: 0.73 },
  { key: "perfect_for", en: "perfect for", zh: "适合", count: 6, source: "dictionary", confidence: 1 },
  { key: "scooter_for", en: "scooter for", zh: "滑板车", count: 6, source: "word", confidence: 0.9 },
  { key: "babies_and", en: "babies and", zh: "婴儿", count: 6, source: "dictionary", confidence: 1 },
  { key: "50_canopy", en: "50 canopy", zh: "50顶篷", count: 6, source: "word", confidence: 0.9 },
  { key: "bluetooth", en: "bluetooth", zh: "蓝牙", count: 6, source: "dictionary", confidence: 1 },
  { key: "12_14_16", en: "12 14 16", zh: "121416", count: 6, source: "word", confidence: 0.9 },
  { key: "car_for", en: "car for", zh: "车", count: 6, source: "word", confidence: 0.9 },
  { key: "carrier", en: "carrier", zh: "背带", count: 6, source: "dictionary", confidence: 1 },
  { key: "jogging", en: "jogging", zh: "慢跑", count: 6, source: "dictionary", confidence: 1 },
  { key: "old_boy", en: "old boy", zh: "男童", count: 6, source: "dictionary", confidence: 1 },
  { key: "perfect", en: "perfect", zh: "理想", count: 6, source: "dictionary", confidence: 1 },
  { key: "babies", en: "babies", zh: "婴儿", count: 6, source: "dictionary", confidence: 1 },
  { key: "little", en: "little", zh: "小号", count: 6, source: "dictionary", confidence: 1 },
  { key: "upf_50", en: "upf 50", zh: "upf50", count: 6, source: "word", confidence: 0.73 },
  { key: "12_14", en: "12 14", zh: "1214", count: 6, source: "word", confidence: 0.9 },
  { key: "14_16", en: "14 16", zh: "1416", count: 6, source: "word", confidence: 0.9 },
  { key: "month", en: "month", zh: "个月", count: 6, source: "dictionary", confidence: 1 },
  { key: "trike", en: "trike", zh: "三轮车", count: 6, source: "dictionary", confidence: 1 },
  { key: "ultra", en: "ultra", zh: "超轻", count: 6, source: "dictionary", confidence: 1 },
  { key: "in_1", en: "in 1", zh: "1", count: 6, source: "word", confidence: 0.9 },
  { key: "pink", en: "pink", zh: "粉色", count: 6, source: "word", confidence: 0.9 },
  { key: "play", en: "play", zh: "玩耍", count: 6, source: "dictionary", confidence: 1 },
  { key: "one", en: "one", zh: "", count: 6, source: "pending", confidence: 0 },
  { key: "upf", en: "upf", zh: "UPF", count: 6, source: "dictionary", confidence: 1 },
  { key: "frame_compact_airplane_friendly_one_handed", en: "frame compact airplane-friendly one-handed", zh: "车架紧凑airplane-friendlyone-handed", count: 5, source: "word", confidence: 0.73 },
  { key: "compact_airplane_friendly_one_handed_fold", en: "compact airplane-friendly one-handed fold", zh: "紧凑airplane-friendlyone-handed折叠", count: 5, source: "word", confidence: 0.73 },
  { key: "fiber_frame_compact_airplane_friendly", en: "fiber frame compact airplane-friendly", zh: "fiber车架紧凑airplane-friendly", count: 5, source: "word", confidence: 0.73 },
  { key: "airplane_friendly_one_handed_fold_11", en: "airplane-friendly one-handed fold 11", zh: "airplane-friendlyone-handed折叠11", count: 5, source: "word", confidence: 0.73 },
  { key: "compact_airplane_friendly_one_handed", en: "compact airplane-friendly one-handed", zh: "紧凑可登机单手", count: 5, source: "dictionary", confidence: 1 },
  { key: "airplane_friendly_one_handed_fold", en: "airplane-friendly one-handed fold", zh: "可登机单手折叠", count: 5, source: "dictionary", confidence: 1 },
  { key: "lightweight_baby_travel_stroller", en: "lightweight baby travel stroller", zh: "轻量婴儿旅行推车", count: 5, source: "word", confidence: 0.9 },
  { key: "frame_compact_airplane_friendly", en: "frame compact airplane-friendly", zh: "车架紧凑airplane-friendly", count: 5, source: "word", confidence: 0.78 },
  { key: "mamazing_ultra_air_lightweight", en: "mamazing ultra air lightweight", zh: "Mamazing 超轻空气轻量", count: 5, source: "dictionary", confidence: 1 },
  { key: "airplane_friendly_one_handed", en: "airplane-friendly one-handed", zh: "可登机单手", count: 5, source: "dictionary", confidence: 1 },
  { key: "10_36_month_toddler_balance", en: "10-36 month toddler balance", zh: "10-36month儿童平衡", count: 5, source: "word", confidence: 0.73 },
  { key: "air_lightweight_baby_travel", en: "air lightweight baby travel", zh: "air轻量婴儿旅行", count: 5, source: "word", confidence: 0.81 },
  { key: "travel_stroller_with_carbon", en: "travel stroller with carbon", zh: "旅行推车碳", count: 5, source: "word", confidence: 0.9 },
  { key: "carbon_fiber_frame_compact", en: "carbon fiber frame compact", zh: "碳fiber车架紧凑", count: 5, source: "word", confidence: 0.81 },
  { key: "stroller_with_carbon_fiber", en: "stroller with carbon fiber", zh: "推车碳fiber", count: 5, source: "word", confidence: 0.78 },
  { key: "ultra_air_lightweight_baby", en: "ultra air lightweight baby", zh: "ultraair轻量婴儿", count: 5, source: "word", confidence: 0.73 },
  { key: "baby_travel_stroller_with", en: "baby travel stroller with", zh: "婴儿旅行推车", count: 5, source: "word", confidence: 0.9 },
  { key: "compact_airplane_friendly", en: "compact airplane-friendly", zh: "紧凑airplane-friendly", count: 5, source: "word", confidence: 0.73 },
  { key: "lightweight_baby_travel", en: "lightweight baby travel", zh: "轻量婴儿旅行", count: 5, source: "word", confidence: 0.9 },
  { key: "with_carbon_fiber_frame", en: "with carbon fiber frame", zh: "碳fiber车架", count: 5, source: "word", confidence: 0.78 },
  { key: "ultra_air_lightweight", en: "ultra air lightweight", zh: "超轻空气轻量", count: 5, source: "dictionary", confidence: 1 },
  { key: "air_lightweight_baby", en: "air lightweight baby", zh: "air轻量婴儿", count: 5, source: "word", confidence: 0.78 },
  { key: "baby_travel_stroller", en: "baby travel stroller", zh: "婴儿旅行推车", count: 5, source: "word", confidence: 0.9 },
  { key: "lightweight_stroller", en: "lightweight stroller", zh: "轻量推车", count: 5, source: "word", confidence: 0.9 },
  { key: "one_handed_fold_11_6", en: "one-handed fold 11 6", zh: "one-handed折叠116", count: 5, source: "word", confidence: 0.81 },
  { key: "stroller_lightweight", en: "stroller lightweight", zh: "推车轻量", count: 5, source: "word", confidence: 0.9 },
  { key: "stroller_with_carbon", en: "stroller with carbon", zh: "推车碳", count: 5, source: "word", confidence: 0.9 },
  { key: "10_36_month_toddler", en: "10-36 month toddler", zh: "10-36 个月儿童", count: 5, source: "dictionary", confidence: 1 },
  { key: "fiber_frame_compact", en: "fiber frame compact", zh: "fiber车架紧凑", count: 5, source: "word", confidence: 0.78 },
  { key: "baby_stroller_with", en: "baby stroller with", zh: "婴儿推车", count: 5, source: "word", confidence: 0.9 },
  { key: "carbon_fiber_frame", en: "carbon fiber frame", zh: "碳fiber车架", count: 5, source: "word", confidence: 0.78 },
  { key: "mamazing_ultra_air", en: "mamazing ultra air", zh: "", count: 5, source: "pending", confidence: 0 },
  { key: "one_handed_fold_11", en: "one-handed fold 11", zh: "one-handed折叠11", count: 5, source: "word", confidence: 0.78 },
  { key: "travel_system_with", en: "travel system with", zh: "旅行系统", count: 5, source: "word", confidence: 0.9 },
  { key: "airplane_friendly", en: "airplane-friendly", zh: "可登机", count: 5, source: "dictionary", confidence: 1 },
  { key: "balance_bike_with", en: "balance bike with", zh: "平衡自行车", count: 5, source: "word", confidence: 0.9 },
  { key: "with_carbon_fiber", en: "with carbon fiber", zh: "碳fiber", count: 5, source: "word", confidence: 0.73 },
  { key: "for_toddlers_1_3", en: "for toddlers 1-3", zh: "儿童1-3", count: 5, source: "word", confidence: 0.73 },
  { key: "lightweight_baby", en: "lightweight baby", zh: "轻量婴儿", count: 5, source: "word", confidence: 0.9 },
  { key: "scooter_for_kids", en: "scooter for kids", zh: "滑板车儿童", count: 5, source: "word", confidence: 0.9 },
  { key: "toddler_bike_for", en: "toddler bike for", zh: "儿童自行车", count: 5, source: "word", confidence: 0.9 },
  { key: "air_lightweight", en: "air lightweight", zh: "air轻量", count: 5, source: "word", confidence: 0.73 },
  { key: "one_handed_fold", en: "one-handed fold", zh: "one-handed折叠", count: 5, source: "word", confidence: 0.73 },
  { key: "1_year_old_boy", en: "1 year old boy", zh: "1岁boy", count: 5, source: "word", confidence: 0.78 },
  { key: "first_birthday", en: "first birthday", zh: "一岁生日", count: 5, source: "dictionary", confidence: 1 },
  { key: "mamazing_ultra", en: "mamazing ultra", zh: "Mamazing Ultra", count: 5, source: "dictionary", confidence: 1 },
  { key: "fold_11_6_lbs", en: "fold 11 6 lbs", zh: "折叠116lbs", count: 5, source: "word", confidence: 0.81 },
  { key: "frame_compact", en: "frame compact", zh: "车架紧凑", count: 5, source: "word", confidence: 0.9 },
  { key: "with_training", en: "with training", zh: "辅助", count: 5, source: "word", confidence: 0.9 },
  { key: "12_24_months", en: "12-24 months", zh: "12-24 个月", count: 5, source: "dictionary", confidence: 1 },
  { key: "baby_carrier", en: "baby carrier", zh: "婴儿carrier", count: 5, source: "word", confidence: 0.73 },
  { key: "bicycle_with", en: "bicycle with", zh: "自行车", count: 5, source: "word", confidence: 0.9 },
  { key: "car_for_kids", en: "car for kids", zh: "车儿童", count: 5, source: "word", confidence: 0.9 },
  { key: "carbon_fiber", en: "carbon fiber", zh: "碳fiber", count: 5, source: "word", confidence: 0.73 },
  { key: "toddlers_1_3", en: "toddlers 1-3", zh: "儿童1-3", count: 5, source: "word", confidence: 0.73 },
  { key: "10_36_month", en: "10-36 month", zh: "10-36 个月", count: 5, source: "dictionary", confidence: 1 },
  { key: "fiber_frame", en: "fiber frame", zh: "fiber车架", count: 5, source: "word", confidence: 0.73 },
  { key: "system_with", en: "system with", zh: "系统", count: 5, source: "word", confidence: 0.9 },
  { key: "with_carbon", en: "with carbon", zh: "碳", count: 5, source: "word", confidence: 0.9 },
  { key: "first_bike", en: "first bike", zh: "first自行车", count: 5, source: "word", confidence: 0.73 },
  { key: "one_handed", en: "one-handed", zh: "单手", count: 5, source: "dictionary", confidence: 1 },
  { key: "certified", en: "certified", zh: "认证", count: 5, source: "dictionary", confidence: 1 },
  { key: "ergonomic", en: "ergonomic", zh: "人体工学", count: 5, source: "dictionary", confidence: 1 },
  { key: "fold_11_6", en: "fold 11 6", zh: "折叠116", count: 5, source: "word", confidence: 0.9 },
  { key: "handlebar", en: "handlebar", zh: "车把", count: 5, source: "word", confidence: 0.9 },
  { key: "infant_to", en: "infant to", zh: "婴儿", count: 5, source: "word", confidence: 0.9 },
  { key: "ultra_air", en: "ultra air", zh: "超轻空气", count: 5, source: "dictionary", confidence: 1 },
  { key: "11_6_lbs", en: "11 6 lbs", zh: "116lbs", count: 5, source: "word", confidence: 0.78 },
  { key: "airplane", en: "airplane", zh: "飞机", count: 5, source: "dictionary", confidence: 1 },
  { key: "for_boys", en: "for boys", zh: "男孩", count: 5, source: "word", confidence: 0.9 },
  { key: "licensed", en: "licensed", zh: "官方授权", count: 5, source: "dictionary", confidence: 1 },
  { key: "mamazing", en: "mamazing", zh: "Mamazing", count: 5, source: "dictionary", confidence: 1 },
  { key: "push_car", en: "push car", zh: "推行车", count: 5, source: "word", confidence: 0.9 },
  { key: "5_point", en: "5-point", zh: "五点式", count: 5, source: "dictionary", confidence: 1 },
  { key: "classic", en: "classic", zh: "经典", count: 5, source: "dictionary", confidence: 1 },
  { key: "evenflo", en: "evenflo", zh: "Evenflo", count: 5, source: "dictionary", confidence: 1 },
  { key: "fold_11", en: "fold 11", zh: "折叠11", count: 5, source: "word", confidence: 0.9 },
  { key: "newborn", en: "newborn", zh: "新生儿", count: 5, source: "dictionary", confidence: 1 },
  { key: "playard", en: "playard", zh: "游戏床", count: 5, source: "dictionary", confidence: 1 },
  { key: "2_year", en: "2 year", zh: "2岁", count: 5, source: "word", confidence: 0.9 },
  { key: "3_in_1", en: "3-in-1", zh: "3 合 1", count: 5, source: "pattern", confidence: 0.9 },
  { key: "4_in_1", en: "4-in-1", zh: "4 合 1", count: 5, source: "pattern", confidence: 0.9 },
  { key: "5_in_1", en: "5-in-1", zh: "5 合 1", count: 5, source: "pattern", confidence: 0.9 },
  { key: "handle", en: "handle", zh: "把手", count: 5, source: "word", confidence: 0.9 },
  { key: "on_toy", en: "on toy", zh: "玩具", count: 5, source: "word", confidence: 0.9 },
  { key: "10_36", en: "10-36", zh: "10-36 个月", count: 5, source: "dictionary", confidence: 1 },
  { key: "6_lbs", en: "6 lbs", zh: "6lbs", count: 5, source: "word", confidence: 0.73 },
  { key: "extra", en: "extra", zh: "额外", count: 5, source: "dictionary", confidence: 1 },
  { key: "fiber", en: "fiber", zh: "纤维", count: 5, source: "dictionary", confidence: 1 },
  { key: "quick", en: "quick", zh: "快速", count: 5, source: "dictionary", confidence: 1 },
  { key: "white", en: "white", zh: "白色", count: 5, source: "word", confidence: 0.9 },
  { key: "11_6", en: "11 6", zh: "116", count: 5, source: "word", confidence: 0.9 },
  { key: "gray", en: "gray", zh: "灰色", count: 5, source: "word", confidence: 0.9 },
  { key: "mini", en: "mini", zh: "迷你", count: 5, source: "dictionary", confidence: 1 },
  { key: "rear", en: "rear", zh: "后置", count: 5, source: "dictionary", confidence: 1 },
  { key: "2_5", en: "2-5", zh: "2-5 岁", count: 5, source: "dictionary", confidence: 1 },
  { key: "age", en: "age", zh: "年龄", count: 5, source: "word", confidence: 0.9 },
  { key: "air", en: "air", zh: "空气", count: 5, source: "dictionary", confidence: 1 },
  { key: "mph", en: "mph", zh: "英里/小时", count: 5, source: "dictionary", confidence: 1 },
  { key: "sit", en: "sit", zh: "可坐", count: 5, source: "dictionary", confidence: 1 },
  { key: "gifts_10_36_month_toddler", en: "gifts 10-36 month toddler", zh: "10-36 个月儿童礼物", count: 4, source: "dictionary", confidence: 1 },
  { key: "tricycle_for_toddlers_1_3", en: "tricycle for toddlers 1-3", zh: "三轮车儿童1-3", count: 4, source: "word", confidence: 0.78 },
  { key: "lbs_perfect_for_toddlers", en: "lbs perfect for toddlers", zh: "适合儿童", count: 4, source: "dictionary", confidence: 1 },
  { key: "for_babies_and_toddlers", en: "for babies and toddlers", zh: "babies儿童", count: 4, source: "word", confidence: 0.73 },
  { key: "toddler_balance_bike_no", en: "toddler balance bike no", zh: "儿童平衡自行车no", count: 4, source: "word", confidence: 0.81 },
  { key: "baby_carrier_ergonomic", en: "baby carrier ergonomic", zh: "人体工学婴儿背带", count: 4, source: "dictionary", confidence: 1 },
  { key: "multi_position_recline", en: "multi-position recline", zh: "multi-position可躺", count: 4, source: "word", confidence: 0.73 },
  { key: "toddler_balance_bike_2", en: "toddler balance bike 2", zh: "儿童平衡自行车2", count: 4, source: "word", confidence: 0.9 },
  { key: "balance_bike_no_pedal", en: "balance bike no pedal", zh: "平衡自行车nopedal", count: 4, source: "word", confidence: 0.73 },
  { key: "umbrella_stroller_for", en: "umbrella stroller for", zh: "umbrella推车", count: 4, source: "word", confidence: 0.73 },
  { key: "perfect_for_toddlers", en: "perfect for toddlers", zh: "perfect儿童", count: 4, source: "word", confidence: 0.73 },
  { key: "with_training_wheels", en: "with training wheels", zh: "辅助轮", count: 4, source: "word", confidence: 0.9 },
  { key: "balance_bike_2_year", en: "balance bike 2 year", zh: "平衡自行车2岁", count: 4, source: "word", confidence: 0.9 },
  { key: "infant_and_toddler", en: "infant and toddler", zh: "婴儿儿童", count: 4, source: "word", confidence: 0.9 },
  { key: "lightweight_travel", en: "lightweight travel", zh: "轻量旅行", count: 4, source: "word", confidence: 0.9 },
  { key: "twin_baby_stroller", en: "twin baby stroller", zh: "twin婴儿推车", count: 4, source: "word", confidence: 0.78 },
  { key: "6_lbs_perfect_for", en: "6 lbs perfect for", zh: "适合 6 磅", count: 4, source: "dictionary", confidence: 1 },
  { key: "carrier_ergonomic", en: "carrier ergonomic", zh: "人体工学背带", count: 4, source: "dictionary", confidence: 1 },
  { key: "gifts_10_36_month", en: "gifts 10-36 month", zh: "10-36 个月礼物", count: 4, source: "dictionary", confidence: 1 },
  { key: "infant_to_toddler", en: "infant to toddler", zh: "婴儿儿童", count: 4, source: "word", confidence: 0.9 },
  { key: "11_6_lbs_perfect", en: "11 6 lbs perfect", zh: "116lbsperfect", count: 4, source: "word", confidence: 0.73 },
  { key: "electric_scooter", en: "electric scooter", zh: "电动滑板车", count: 4, source: "word", confidence: 0.9 },
  { key: "toddler_stroller", en: "toddler stroller", zh: "儿童推车", count: 4, source: "word", confidence: 0.9 },
  { key: "1_year_old_boys", en: "1 year old boys", zh: "1岁男孩", count: 4, source: "word", confidence: 0.9 },
  { key: "balance_bike_no", en: "balance bike no", zh: "平衡自行车no", count: 4, source: "word", confidence: 0.78 },
  { key: "bike_2_year_old", en: "bike 2 year old", zh: "自行车2岁", count: 4, source: "word", confidence: 0.9 },
  { key: "bike_for_1_year", en: "bike for 1 year", zh: "自行车1岁", count: 4, source: "word", confidence: 0.9 },
  { key: "bike_no_pedal_4", en: "bike no pedal 4", zh: "自行车nopedal4", count: 4, source: "word", confidence: 0.73 },
  { key: "lbs_perfect_for", en: "lbs perfect for", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "balance_bike_2", en: "balance bike 2", zh: "平衡自行车2", count: 4, source: "word", confidence: 0.9 },
  { key: "delta_children", en: "delta children", zh: "Delta Children", count: 4, source: "dictionary", confidence: 1 },
  { key: "for_babies_and", en: "for babies and", zh: "适用于婴儿", count: 4, source: "dictionary", confidence: 1 },
  { key: "inch_kids_bike", en: "inch kids bike", zh: "英寸儿童自行车", count: 4, source: "word", confidence: 0.9 },
  { key: "multi_position", en: "multi-position", zh: "多档位", count: 4, source: "dictionary", confidence: 1 },
  { key: "wagon_for_kids", en: "wagon for kids", zh: "拖车儿童", count: 4, source: "word", confidence: 0.9 },
  { key: "2_5_years_old", en: "2-5 years old", zh: "2-5 岁", count: 4, source: "pattern", confidence: 0.94 },
  { key: "3_5_year_olds", en: "3-5 year olds", zh: "3-5 岁儿童", count: 4, source: "dictionary", confidence: 1 },
  { key: "3_5_years_old", en: "3-5 years old", zh: "3-5 岁", count: 4, source: "pattern", confidence: 0.94 },
  { key: "6_lbs_perfect", en: "6 lbs perfect", zh: "6 磅适合", count: 4, source: "dictionary", confidence: 1 },
  { key: "bike_no_pedal", en: "bike no pedal", zh: "无脚踏自行车", count: 4, source: "dictionary", confidence: 1 },
  { key: "kids_bike_for", en: "kids bike for", zh: "儿童自行车", count: 4, source: "word", confidence: 0.9 },
  { key: "mompush_lithe", en: "mompush lithe", zh: "Mompush Lithe", count: 4, source: "dictionary", confidence: 1 },
  { key: "parent_remote", en: "parent remote", zh: "parent遥控", count: 4, source: "word", confidence: 0.73 },
  { key: "toddler_first", en: "toddler first", zh: "儿童first", count: 4, source: "word", confidence: 0.73 },
  { key: "twin_stroller", en: "twin stroller", zh: "twin推车", count: 4, source: "word", confidence: 0.73 },
  { key: "year_old_boys", en: "year old boys", zh: "岁男孩", count: 4, source: "word", confidence: 0.9 },
  { key: "baby_playard", en: "baby playard", zh: "婴儿playard", count: 4, source: "word", confidence: 0.73 },
  { key: "kick_scooter", en: "kick scooter", zh: "滑板车", count: 4, source: "dictionary", confidence: 1 },
  { key: "kids_bicycle", en: "kids bicycle", zh: "儿童自行车", count: 4, source: "word", confidence: 0.9 },
  { key: "kids_ride_on", en: "kids ride on", zh: "儿童骑乘", count: 4, source: "word", confidence: 0.9 },
  { key: "toy_for_ages", en: "toy for ages", zh: "玩具年龄", count: 4, source: "word", confidence: 0.9 },
  { key: "toy_for_kids", en: "toy for kids", zh: "玩具儿童", count: 4, source: "word", confidence: 0.9 },
  { key: "12_14_16_18", en: "12 14 16 18", zh: "12141618", count: 4, source: "word", confidence: 0.9 },
  { key: "bike_2_year", en: "bike 2 year", zh: "自行车2岁", count: 4, source: "word", confidence: 0.9 },
  { key: "gifts_10_36", en: "gifts 10-36", zh: "10-36 个月礼物", count: 4, source: "dictionary", confidence: 1 },
  { key: "lbs_perfect", en: "lbs perfect", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "push_walker", en: "push walker", zh: "推行walker", count: 4, source: "word", confidence: 0.73 },
  { key: "2_year_old", en: "2 year old", zh: "2岁", count: 4, source: "word", confidence: 0.9 },
  { key: "bike_for_1", en: "bike for 1", zh: "自行车1", count: 4, source: "word", confidence: 0.9 },
  { key: "for_babies", en: "for babies", zh: "适用于婴儿", count: 4, source: "dictionary", confidence: 1 },
  { key: "for_infant", en: "for infant", zh: "婴儿", count: 4, source: "word", confidence: 0.9 },
  { key: "girl_gifts", en: "girl gifts", zh: "女孩礼物", count: 4, source: "dictionary", confidence: 1 },
  { key: "infant_and", en: "infant and", zh: "婴儿", count: 4, source: "word", confidence: 0.9 },
  { key: "no_pedal_4", en: "no pedal 4", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "reversible", en: "reversible", zh: "可双向", count: 4, source: "dictionary", confidence: 1 },
  { key: "kids_ride", en: "kids ride", zh: "儿童骑乘", count: 4, source: "word", confidence: 0.9 },
  { key: "removable", en: "removable", zh: "可拆卸", count: 4, source: "dictionary", confidence: 1 },
  { key: "twin_baby", en: "twin baby", zh: "twin婴儿", count: 4, source: "word", confidence: 0.73 },
  { key: "year_olds", en: "year olds", zh: "岁olds", count: 4, source: "word", confidence: 0.73 },
  { key: "14_16_18", en: "14 16 18", zh: "141618", count: 4, source: "word", confidence: 0.9 },
  { key: "3_5_year", en: "3-5 year", zh: "3-5岁", count: 4, source: "word", confidence: 0.73 },
  { key: "activity", en: "activity", zh: "活动", count: 4, source: "dictionary", confidence: 1 },
  { key: "approved", en: "approved", zh: "认证通过", count: 4, source: "dictionary", confidence: 1 },
  { key: "car_with", en: "car with", zh: "车", count: 4, source: "word", confidence: 0.9 },
  { key: "converts", en: "converts", zh: "可转换", count: 4, source: "dictionary", confidence: 1 },
  { key: "included", en: "included", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "mattress", en: "mattress", zh: "床垫", count: 4, source: "dictionary", confidence: 1 },
  { key: "old_boys", en: "old boys", zh: "男孩", count: 4, source: "word", confidence: 0.9 },
  { key: "pramette", en: "pramette", zh: "婴儿摇篮模式", count: 4, source: "dictionary", confidence: 1 },
  { key: "bike_no", en: "bike no", zh: "自行车no", count: 4, source: "word", confidence: 0.73 },
  { key: "durable", en: "durable", zh: "耐用", count: 4, source: "dictionary", confidence: 1 },
  { key: "easy_to", en: "easy to", zh: "易于", count: 4, source: "dictionary", confidence: 1 },
  { key: "joystar", en: "joystar", zh: "Joystar", count: 4, source: "dictionary", confidence: 1 },
  { key: "pedal_4", en: "pedal 4", zh: "pedal4", count: 4, source: "word", confidence: 0.73 },
  { key: "umatoll", en: "umatoll", zh: "Umatoll", count: 4, source: "dictionary", confidence: 1 },
  { key: "vehicle", en: "vehicle", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "6_in_1", en: "6-in-1", zh: "6 合 1", count: 4, source: "pattern", confidence: 0.9 },
  { key: "bike_2", en: "bike 2", zh: "自行车2", count: 4, source: "word", confidence: 0.9 },
  { key: "design", en: "design", zh: "设计", count: 4, source: "dictionary", confidence: 1 },
  { key: "weight", en: "weight", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "16_18", en: "16 18", zh: "1618", count: 4, source: "word", confidence: 0.9 },
  { key: "combo", en: "combo", zh: "组合", count: 4, source: "dictionary", confidence: 1 },
  { key: "delta", en: "delta", zh: "Delta", count: 4, source: "dictionary", confidence: 1 },
  { key: "glerc", en: "glerc", zh: "Glerc", count: 4, source: "dictionary", confidence: 1 },
  { key: "lithe", en: "lithe", zh: "Lithe", count: 4, source: "dictionary", confidence: 1 },
  { key: "motor", en: "motor", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "music", en: "music", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "plate", en: "plate", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "stand", en: "stand", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "style", en: "style", zh: "风格", count: 4, source: "word", confidence: 0.9 },
  { key: "truck", en: "truck", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "up_to", en: "up to", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "wheel", en: "wheel", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "best", en: "best", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "dual", en: "dual", zh: "双模式", count: 4, source: "dictionary", confidence: 1 },
  { key: "jeep", en: "jeep", zh: "Jeep", count: 4, source: "dictionary", confidence: 1 },
  { key: "kick", en: "kick", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "mode", en: "mode", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "olds", en: "olds", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "side", en: "side", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "tray", en: "tray", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "2_3", en: "2-3", zh: "2-3 岁", count: 4, source: "dictionary", confidence: 1 },
  { key: "3_5", en: "3-5", zh: "3-5 岁", count: 4, source: "dictionary", confidence: 1 },
  { key: "use", en: "use", zh: "", count: 4, source: "pending", confidence: 0 },
  { key: "carbon_travel_stroller_ultra_lightweight", en: "carbon travel stroller ultra-lightweight", zh: "碳旅行推车ultra-lightweight", count: 3, source: "word", confidence: 0.81 },
  { key: "approved_one_second_auto_fold_one_hand", en: "approved one-second auto-fold one-hand", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "carry_on_approved_one_second_auto_fold", en: "carry-on approved one-second auto-fold", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "airplane_carry_on_approved_one_second", en: "airplane carry-on approved one-second", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "travel_stroller_ultra_lightweight_11", en: "travel stroller ultra-lightweight 11", zh: "旅行推车ultra-lightweight11", count: 3, source: "word", confidence: 0.81 },
  { key: "compact_airplane_carry_on_approved", en: "compact airplane carry-on approved", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "one_second_auto_fold_one_hand_full", en: "one-second auto-fold one-hand full", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "stroller_lightweight_stroller_with", en: "stroller lightweight stroller with", zh: "推车轻量推车", count: 3, source: "word", confidence: 0.9 },
  { key: "travel_stroller_ultra_lightweight", en: "travel stroller ultra-lightweight", zh: "旅行推车ultra-lightweight", count: 3, source: "word", confidence: 0.78 },
  { key: "adjustable_canopy_storage_basket", en: "adjustable canopy storage basket", zh: "可调节顶篷储物篮", count: 3, source: "word", confidence: 0.9 },
  { key: "auto_fold_one_hand_full_recline", en: "auto-fold one-hand full recline", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "stroller_ultra_lightweight_11_5", en: "stroller ultra-lightweight 11 5", zh: "推车ultra-lightweight115", count: 3, source: "word", confidence: 0.81 },
  { key: "approved_one_second_auto_fold", en: "approved one-second auto-fold", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "lbs_compact_airplane_carry_on", en: "lbs compact airplane carry-on", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "one_second_auto_fold_one_hand", en: "one-second auto-fold one-hand", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "playard_breathable_mesh_sides", en: "playard breathable mesh sides", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "stroller_lightweight_stroller", en: "stroller lightweight stroller", zh: "推车轻量推车", count: 3, source: "word", confidence: 0.9 },
  { key: "stroller_ultra_lightweight_11", en: "stroller ultra-lightweight 11", zh: "推车ultra-lightweight11", count: 3, source: "word", confidence: 0.78 },
  { key: "baby_playard_breathable_mesh", en: "baby playard breathable mesh", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "carry_on_approved_one_second", en: "carry-on approved one-second", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "nexis_carbon_travel_stroller", en: "nexis carbon travel stroller", zh: "nexis碳旅行推车", count: 3, source: "word", confidence: 0.81 },
  { key: "lightweight_travel_stroller", en: "lightweight travel stroller", zh: "轻量旅行推车", count: 3, source: "word", confidence: 0.9 },
  { key: "mompush_nexis_carbon_travel", en: "mompush nexis carbon travel", zh: "mompushnexis碳旅行", count: 3, source: "word", confidence: 0.73 },
  { key: "airplane_carry_on_approved", en: "airplane carry-on approved", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "one_hand_full_recline_from", en: "one-hand full recline from", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "stroller_ultra_lightweight", en: "stroller ultra-lightweight", zh: "推车ultra-lightweight", count: 3, source: "word", confidence: 0.73 },
  { key: "stroller_with_compact_fold", en: "stroller with compact fold", zh: "推车紧凑折叠", count: 3, source: "word", confidence: 0.9 },
  { key: "travel_system_with_litemax", en: "travel system with litemax", zh: "旅行系统litemax", count: 3, source: "word", confidence: 0.78 },
  { key: "ultra_lightweight_11_5_lbs", en: "ultra-lightweight 11 5 lbs", zh: "ultra-lightweight115lbs", count: 3, source: "word", confidence: 0.73 },
  { key: "adjustable_canopy_storage", en: "adjustable canopy storage", zh: "可调节顶篷储物", count: 3, source: "word", confidence: 0.9 },
  { key: "compact_airplane_carry_on", en: "compact airplane carry-on", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "lightweight_stroller_with", en: "lightweight stroller with", zh: "轻量推车", count: 3, source: "word", confidence: 0.9 },
  { key: "colorful_lighting_wheels", en: "colorful lighting wheels", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "auto_fold_one_hand_full", en: "auto-fold one-hand full", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "baby_playard_breathable", en: "baby playard breathable", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "full_recline_from_birth", en: "full recline from birth", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "playard_breathable_mesh", en: "playard breathable mesh", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "5_lbs_compact_airplane", en: "5 lbs compact airplane", zh: "5lbs紧凑airplane", count: 3, source: "word", confidence: 0.73 },
  { key: "baby_balance_bike_with", en: "baby balance bike with", zh: "婴儿平衡自行车", count: 3, source: "word", confidence: 0.9 },
  { key: "carbon_travel_stroller", en: "carbon travel stroller", zh: "碳旅行推车", count: 3, source: "word", confidence: 0.9 },
  { key: "girl_gifts_10_36_month", en: "girl gifts 10-36 month", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "ultra_lightweight_11_5", en: "ultra-lightweight 11 5", zh: "ultra-lightweight115", count: 3, source: "word", confidence: 0.78 },
  { key: "50_lbs_jpma_certified", en: "50 lbs jpma certified", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "breathable_mesh_sides", en: "breathable mesh sides", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "canopy_storage_basket", en: "canopy storage basket", zh: "顶篷储物篮", count: 3, source: "word", confidence: 0.9 },
  { key: "for_ages_12_24_months", en: "for ages 12-24 months", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "one_hand_full_recline", en: "one-hand full recline", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "parent_remote_control", en: "parent remote control", zh: "parent遥控控制", count: 3, source: "word", confidence: 0.78 },
  { key: "recline_from_birth_to", en: "recline from birth to", zh: "可躺birth", count: 3, source: "word", confidence: 0.73 },
  { key: "stroller_with_compact", en: "stroller with compact", zh: "推车紧凑", count: 3, source: "word", confidence: 0.9 },
  { key: "adjustable_handlebar", en: "adjustable handlebar", zh: "可调节车把", count: 3, source: "word", confidence: 0.9 },
  { key: "double_stroller_twin", en: "double stroller twin", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "first_birthday_gifts", en: "first birthday gifts", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "lbs_compact_airplane", en: "lbs compact airplane", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "mompush_nexis_carbon", en: "mompush nexis carbon", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "one_second_auto_fold", en: "one-second auto-fold", zh: "一秒自动折叠", count: 3, source: "dictionary", confidence: 1 },
  { key: "toddler_tricycle_for", en: "toddler tricycle for", zh: "儿童三轮车", count: 3, source: "word", confidence: 0.9 },
  { key: "ultra_lightweight_11", en: "ultra-lightweight 11", zh: "ultra-lightweight11", count: 3, source: "word", confidence: 0.73 },
  { key: "adjustable_backrest", en: "adjustable backrest", zh: "可调节backrest", count: 3, source: "word", confidence: 0.73 },
  { key: "approved_one_second", en: "approved one-second", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "infant_car_seat_and", en: "infant car seat and", zh: "婴儿车座椅", count: 3, source: "word", confidence: 0.9 },
  { key: "nexis_carbon_travel", en: "nexis carbon travel", zh: "nexis碳旅行", count: 3, source: "word", confidence: 0.78 },
  { key: "system_with_litemax", en: "system with litemax", zh: "系统litemax", count: 3, source: "word", confidence: 0.73 },
  { key: "year_old_boys_girls", en: "year old boys girls", zh: "岁男孩女孩", count: 3, source: "word", confidence: 0.9 },
  { key: "auto_fold_one_hand", en: "auto-fold one-hand", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "bike_birthday_gift", en: "bike birthday gift", zh: "自行车birthday", count: 3, source: "word", confidence: 0.73 },
  { key: "bike_with_training", en: "bike with training", zh: "自行车辅助", count: 3, source: "word", confidence: 0.9 },
  { key: "for_2_3_boys_girls", en: "for 2-3 boys girls", zh: "2-3男孩女孩", count: 3, source: "word", confidence: 0.78 },
  { key: "lbs_jpma_certified", en: "lbs jpma certified", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "newborn_to_toddler", en: "newborn to toddler", zh: "newborn儿童", count: 3, source: "word", confidence: 0.73 },
  { key: "playard_breathable", en: "playard breathable", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "recline_from_birth", en: "recline from birth", zh: "可躺birth", count: 3, source: "word", confidence: 0.73 },
  { key: "toy_for_ages_12_24", en: "toy for ages 12-24", zh: "玩具年龄12-24", count: 3, source: "word", confidence: 0.78 },
  { key: "1_3_3_5_year_olds", en: "1-3 3-5 year olds", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "adjustable_canopy", en: "adjustable canopy", zh: "可调节顶篷", count: 3, source: "word", confidence: 0.9 },
  { key: "ages_12_24_months", en: "ages 12-24 months", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "airplane_carry_on", en: "airplane carry-on", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "by_delta_children", en: "by delta children", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "carry_on_approved", en: "carry-on approved", zh: "可随身登机", count: 3, source: "dictionary", confidence: 1 },
  { key: "full_recline_from", en: "full recline from", zh: "full可躺", count: 3, source: "word", confidence: 0.73 },
  { key: "in_1_toddler_bike", en: "in 1 toddler bike", zh: "1儿童自行车", count: 3, source: "word", confidence: 0.9 },
  { key: "retrospec_cricket", en: "retrospec cricket", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "ultra_lightweight", en: "ultra-lightweight", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "with_compact_fold", en: "with compact fold", zh: "紧凑折叠", count: 3, source: "word", confidence: 0.9 },
  { key: "11_5_lbs_compact", en: "11 5 lbs compact", zh: "115lbs紧凑", count: 3, source: "word", confidence: 0.81 },
  { key: "balance_bike_for", en: "balance bike for", zh: "平衡自行车", count: 3, source: "word", confidence: 0.9 },
  { key: "compact_airplane", en: "compact airplane", zh: "紧凑airplane", count: 3, source: "word", confidence: 0.73 },
  { key: "electric_ride_on", en: "electric ride on", zh: "电动骑乘", count: 3, source: "word", confidence: 0.9 },
  { key: "from_birth_to_50", en: "from birth to 50", zh: "birth50", count: 3, source: "word", confidence: 0.73 },
  { key: "girl_gifts_10_36", en: "girl gifts 10-36", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "ride_on_car_with", en: "ride on car with", zh: "骑乘车", count: 3, source: "word", confidence: 0.9 },
  { key: "ride_on_push_car", en: "ride on push car", zh: "骑乘推行车", count: 3, source: "word", confidence: 0.9 },
  { key: "ride_on_toys_for", en: "ride on toys for", zh: "骑乘玩具", count: 3, source: "word", confidence: 0.9 },
  { key: "with_push_handle", en: "with push handle", zh: "推行把手", count: 3, source: "word", confidence: 0.9 },
  { key: "12_20_inch_kids", en: "12-20 inch kids", zh: "12-20英寸儿童", count: 3, source: "word", confidence: 0.78 },
  { key: "and_lightweight", en: "and lightweight", zh: "轻量", count: 3, source: "word", confidence: 0.9 },
  { key: "birth_to_50_lbs", en: "birth to 50 lbs", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "breathable_mesh", en: "breathable mesh", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "customize_plate", en: "customize plate", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "lighting_wheels", en: "lighting wheels", zh: "lighting轮", count: 3, source: "word", confidence: 0.73 },
  { key: "reversible_seat", en: "reversible seat", zh: "reversible座椅", count: 3, source: "word", confidence: 0.73 },
  { key: "ride_on_toy_for", en: "ride on toy for", zh: "骑乘玩具", count: 3, source: "word", confidence: 0.9 },
  { key: "toddler_ride_on", en: "toddler ride on", zh: "儿童骑乘", count: 3, source: "word", confidence: 0.9 },
  { key: "weight_capacity", en: "weight capacity", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "1_toddler_bike", en: "1 toddler bike", zh: "1儿童自行车", count: 3, source: "word", confidence: 0.9 },
  { key: "2_3_boys_girls", en: "2-3 boys girls", zh: "2-3男孩女孩", count: 3, source: "word", confidence: 0.78 },
  { key: "5_point_safety", en: "5-point safety", zh: "5-point安全", count: 3, source: "word", confidence: 0.73 },
  { key: "canopy_storage", en: "canopy storage", zh: "顶篷储物", count: 3, source: "word", confidence: 0.9 },
  { key: "for_ages_12_24", en: "for ages 12-24", zh: "年龄12-24", count: 3, source: "word", confidence: 0.73 },
  { key: "for_boys_girls", en: "for boys girls", zh: "男孩女孩", count: 3, source: "word", confidence: 0.9 },
  { key: "infantino_flip", en: "infantino flip", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "jpma_certified", en: "jpma certified", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "kids_bike_with", en: "kids bike with", zh: "儿童自行车", count: 3, source: "word", confidence: 0.9 },
  { key: "lumbar_support", en: "lumbar support", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "old_boys_girls", en: "old boys girls", zh: "男孩女孩", count: 3, source: "word", confidence: 0.9 },
  { key: "safety_harness", en: "safety harness", zh: "安全harness", count: 3, source: "word", confidence: 0.73 },
  { key: "to_50_lbs_jpma", en: "to 50 lbs jpma", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "1_4_years_old", en: "1-4 years old", zh: "1-4 岁", count: 3, source: "pattern", confidence: 0.94 },
  { key: "5_lbs_compact", en: "5 lbs compact", zh: "5lbs紧凑", count: 3, source: "word", confidence: 0.78 },
  { key: "bike_birthday", en: "bike birthday", zh: "自行车birthday", count: 3, source: "word", confidence: 0.73 },
  { key: "carbon_travel", en: "carbon travel", zh: "碳旅行", count: 3, source: "word", confidence: 0.9 },
  { key: "electric_ride", en: "electric ride", zh: "电动骑乘", count: 3, source: "word", confidence: 0.9 },
  { key: "evenflo_pivot", en: "evenflo pivot", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "first_ride_on", en: "first ride on", zh: "first骑乘", count: 3, source: "word", confidence: 0.73 },
  { key: "from_birth_to", en: "from birth to", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "mompush_nexis", en: "mompush nexis", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "mph_top_speed", en: "mph top speed", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "one_hand_fold", en: "one hand fold", zh: "单手折叠", count: 3, source: "dictionary", confidence: 1 },
  { key: "one_hand_fold", en: "one-hand fold", zh: "one-hand折叠", count: 3, source: "word", confidence: 0.73 },
  { key: "one_hand_full", en: "one-hand full", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "stroller_twin", en: "stroller twin", zh: "推车twin", count: 3, source: "word", confidence: 0.73 },
  { key: "toddler_black", en: "toddler black", zh: "儿童黑色", count: 3, source: "word", confidence: 0.9 },
  { key: "wicker_basket", en: "wicker basket", zh: "wicker篮", count: 3, source: "word", confidence: 0.73 },
  { key: "year_old_girl", en: "year old girl", zh: "岁girl", count: 3, source: "word", confidence: 0.73 },
  { key: "years_old_red", en: "years old red", zh: "岁红色", count: 3, source: "word", confidence: 0.9 },
  { key: "1_3_3_5_year", en: "1-3 3-5 year", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "car_seat_and", en: "car seat and", zh: "车座椅", count: 3, source: "word", confidence: 0.9 },
  { key: "electric_car", en: "electric car", zh: "电动车", count: 3, source: "word", confidence: 0.9 },
  { key: "for_2_3_boys", en: "for 2-3 boys", zh: "2-3男孩", count: 3, source: "word", confidence: 0.73 },
  { key: "full_recline", en: "full recline", zh: "full可躺", count: 3, source: "word", confidence: 0.73 },
  { key: "in_1_toddler", en: "in 1 toddler", zh: "1儿童", count: 3, source: "word", confidence: 0.9 },
  { key: "little_tikes", en: "little tikes", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "nexis_carbon", en: "nexis carbon", zh: "nexis碳", count: 3, source: "word", confidence: 0.73 },
  { key: "recline_from", en: "recline from", zh: "可躺", count: 3, source: "word", confidence: 0.9 },
  { key: "ride_on_push", en: "ride on push", zh: "骑乘推行", count: 3, source: "word", confidence: 0.9 },
  { key: "side_by_side", en: "side by side", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "stroller_and", en: "stroller and", zh: "推车", count: 3, source: "word", confidence: 0.9 },
  { key: "toddler_ride", en: "toddler ride", zh: "儿童骑乘", count: 3, source: "word", confidence: 0.9 },
  { key: "with_compact", en: "with compact", zh: "紧凑", count: 3, source: "word", confidence: 0.9 },
  { key: "with_litemax", en: "with litemax", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "14_16_18_20", en: "14 16 18 20", zh: "14161820", count: 3, source: "word", confidence: 0.9 },
  { key: "50_lbs_jpma", en: "50 lbs jpma", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "birth_to_50", en: "birth to 50", zh: "birth50", count: 3, source: "word", confidence: 0.73 },
  { key: "carrier_for", en: "carrier for", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "lbs_compact", en: "lbs compact", zh: "lbs紧凑", count: 3, source: "word", confidence: 0.73 },
  { key: "on_car_with", en: "on car with", zh: "车", count: 3, source: "word", confidence: 0.9 },
  { key: "on_push_car", en: "on push car", zh: "推行车", count: 3, source: "word", confidence: 0.9 },
  { key: "on_toys_for", en: "on toys for", zh: "玩具", count: 3, source: "word", confidence: 0.9 },
  { key: "push_handle", en: "push handle", zh: "推把", count: 3, source: "dictionary", confidence: 1 },
  { key: "ride_on_toy", en: "ride-on toy", zh: "ride-on玩具", count: 3, source: "word", confidence: 0.73 },
  { key: "with_travel", en: "with travel", zh: "旅行", count: 3, source: "word", confidence: 0.9 },
  { key: "12_20_inch", en: "12-20 inch", zh: "12-20英寸", count: 3, source: "word", confidence: 0.73 },
  { key: "ages_12_24", en: "ages 12-24", zh: "年龄12-24", count: 3, source: "word", confidence: 0.73 },
  { key: "breathable", en: "breathable", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "first_ride", en: "first ride", zh: "first骑乘", count: 3, source: "word", confidence: 0.73 },
  { key: "for_travel", en: "for travel", zh: "旅行", count: 3, source: "word", confidence: 0.9 },
  { key: "from_birth", en: "from birth", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "girls_bike", en: "girls bike", zh: "女孩自行车", count: 3, source: "word", confidence: 0.9 },
  { key: "mesh_sides", en: "mesh sides", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "newborn_to", en: "newborn to", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "on_toy_for", en: "on toy for", zh: "玩具", count: 3, source: "word", confidence: 0.9 },
  { key: "one_second", en: "one-second", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "seat_first", en: "seat first", zh: "座椅first", count: 3, source: "word", confidence: 0.73 },
  { key: "suspension", en: "suspension", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "trike_with", en: "trike with", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "1_toddler", en: "1 toddler", zh: "1儿童", count: 3, source: "word", confidence: 0.9 },
  { key: "1_4_years", en: "1-4 years", zh: "1-4岁", count: 3, source: "word", confidence: 0.73 },
  { key: "18_months", en: "18 months", zh: "18months", count: 3, source: "word", confidence: 0.73 },
  { key: "2_5_years", en: "2-5 years", zh: "2-5岁", count: 3, source: "word", confidence: 0.73 },
  { key: "and_girls", en: "and girls", zh: "女孩", count: 3, source: "word", confidence: 0.9 },
  { key: "auto_fold", en: "auto-fold", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "bike_baby", en: "bike baby", zh: "自行车婴儿", count: 3, source: "word", confidence: 0.9 },
  { key: "customize", en: "customize", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "hand_fold", en: "hand fold", zh: "hand折叠", count: 3, source: "word", confidence: 0.73 },
  { key: "infantino", en: "infantino", zh: "", count: 3, source: "pending", confidence: 0 },
  { key: "ingenuity", en: "ingenuity", zh: "", count: 3, source: "pending", confidence: 0 },
];
