#!/usr/bin/env node

import fs from "node:fs/promises";
import path from "node:path";

function parseArg(name, fallback = "") {
  const key = `--${name}=`;
  const matched = process.argv.find((arg) => arg.startsWith(key));
  return matched ? matched.slice(key.length) : fallback;
}

function hasFlag(name) {
  return process.argv.includes(`--${name}`);
}

function printHelp() {
  console.log(`Usage: node scripts/media_stage_images_local.mjs [options]\n\nOptions:\n  --manifestPath=<path>       Input manifest generated by import script\n  --stagingRoot=<path>        Local root for staged assets (default: ./resource/assets/backend-import)\n  --outputManifest=<path>     Output manifest with localPath fields (default: ./tmp/front_image_transfer_manifest.staged.json)\n  --pathMode=<mode>           keep|category-product-kind (default: keep)\n  --skipExisting              Skip downloading if local file already exists\n  --dryRun                    Only plan staging, do not write files\n  --help                      Show this help\n`);
}

function normalizeRelativePath(value) {
  return String(value || "").replace(/\\/g, "/").replace(/^\/+/, "");
}

function safeSlug(text, fallback = "unknown") {
  const normalized = String(text || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return normalized || fallback;
}

function rewriteTargetPath(entry, pathMode) {
  const original = normalizeRelativePath(entry?.targetPath || "");
  if (!original || pathMode === "keep") {
    return original;
  }
  if (pathMode === "category-product-kind") {
    const fileName = path.basename(original);
    const category = safeSlug(entry?.sourceCategoryId, "unknown-category");
    const product = safeSlug(entry?.productId, "unknown-product");
    const kind = safeSlug(entry?.kind, "gallery");
    return `categories/${category}/products/${product}/${kind}/${fileName}`;
  }
  return original;
}

async function readJsonFile(filePath) {
  const full = path.resolve(filePath);
  const raw = await fs.readFile(full, "utf-8");
  return JSON.parse(raw);
}

async function writeJsonFile(filePath, payload) {
  const full = path.resolve(filePath);
  await fs.mkdir(path.dirname(full), { recursive: true });
  await fs.writeFile(full, `${JSON.stringify(payload, null, 2)}\n`, "utf-8");
}

async function fileExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function fetchBinary(url) {
  const response = await fetch(url, {
    headers: {
      Accept: "image/*,application/octet-stream;q=0.8,*/*;q=0.5",
    },
  });
  if (!response.ok) {
    const text = await response.text();
    throw new Error(`download failed ${response.status} ${url} ${text.slice(0, 200)}`);
  }
  const arrayBuffer = await response.arrayBuffer();
  return Buffer.from(arrayBuffer);
}

async function main() {
  if (hasFlag("help")) {
    printHelp();
    return;
  }

  const manifestPath = parseArg("manifestPath", process.env.IMAGE_MANIFEST_PATH || "./tmp/front_image_transfer_manifest.init.json");
  const stagingRoot = parseArg("stagingRoot", "./resource/assets/backend-import");
  const outputManifest = parseArg("outputManifest", "./tmp/front_image_transfer_manifest.staged.json");
  const pathMode = parseArg("pathMode", "keep");
  const skipExisting = hasFlag("skipExisting");
  const dryRun = hasFlag("dryRun");

  const manifestAbs = path.resolve(manifestPath);
  if (!(await fileExists(manifestAbs))) {
    throw new Error(`manifest not found: ${manifestAbs}. Run 'npm run import:cms:init' first or provide --manifestPath=<existing-file>.`);
  }

  const manifest = await readJsonFile(manifestPath);
  const entries = Array.isArray(manifest?.entries) ? manifest.entries : [];
  if (entries.length === 0) {
    throw new Error(`No entries found in manifest: ${manifestPath}`);
  }

  const rootAbs = path.resolve(stagingRoot);
  const importBatchId = String(manifest?.importBatchId || "batch-unknown");

  console.log(`[stage] manifest=${manifestPath}`);
  console.log(`[stage] entries=${entries.length}`);
  console.log(`[stage] stagingRoot=${rootAbs}`);
  console.log(`[stage] pathMode=${pathMode}`);
  console.log(`[stage] dryRun=${dryRun ? "true" : "false"}`);
  console.log(`[stage] skipExisting=${skipExisting ? "true" : "false"}`);

  const result = {
    total: entries.length,
    downloaded: 0,
    skipped: 0,
    failed: 0,
    outputs: [],
  };

  const stagedEntries = [];
  for (let index = 0; index < entries.length; index += 1) {
    const entry = entries[index];
    const sourceUrl = String(entry?.sourceUrl || "").trim();
    const key = rewriteTargetPath(entry, pathMode);
    if (!sourceUrl || !key) {
      result.failed += 1;
      result.outputs.push({ index, sourceUrl, key, status: "failed", error: "missing sourceUrl or targetPath" });
      continue;
    }

    const localAbs = path.join(rootAbs, importBatchId, key);
    const localRel = normalizeRelativePath(path.relative(process.cwd(), localAbs));
    const stagedEntry = {
      ...entry,
      targetPath: key,
      localPath: `./${localRel}`,
    };

    try {
      const exists = await fileExists(localAbs);
      if (exists && skipExisting) {
        result.skipped += 1;
        result.outputs.push({ index, key, localPath: stagedEntry.localPath, sourceUrl, status: "skipped-exists" });
        stagedEntries.push(stagedEntry);
        continue;
      }

      if (dryRun) {
        result.skipped += 1;
        result.outputs.push({ index, key, localPath: stagedEntry.localPath, sourceUrl, status: "dry-run" });
        stagedEntries.push(stagedEntry);
        continue;
      }

      const body = await fetchBinary(sourceUrl);
      await fs.mkdir(path.dirname(localAbs), { recursive: true });
      await fs.writeFile(localAbs, body);

      result.downloaded += 1;
      result.outputs.push({ index, key, localPath: stagedEntry.localPath, sourceUrl, status: "downloaded", size: body.length });
      stagedEntries.push(stagedEntry);
    } catch (err) {
      result.failed += 1;
      result.outputs.push({ index, key, localPath: stagedEntry.localPath, sourceUrl, status: "failed", error: String(err?.message || err) });
      stagedEntries.push(stagedEntry);
    }
  }

  const stagedManifest = {
    ...manifest,
    stagedAt: new Date().toISOString(),
    stagingRoot: rootAbs,
    pathMode,
    entries: stagedEntries,
  };

  await writeJsonFile(outputManifest, stagedManifest);

  const reportPath = path.resolve("./tmp/front_image_stage_report.json");
  await writeJsonFile(reportPath, {
    generatedAt: new Date().toISOString(),
    manifestPath: path.resolve(manifestPath),
    stagedManifestPath: path.resolve(outputManifest),
    stagingRoot: rootAbs,
    importBatchId,
    pathMode,
    ...result,
  });

  console.log("[stage] completed");
  console.log(JSON.stringify({ ...result, stagedManifestPath: path.resolve(outputManifest), reportPath }, null, 2));
}

main().catch((error) => {
  console.error("[stage] failed", error);
  process.exit(1);
});
