#!/usr/bin/env node

import fs from "node:fs/promises";
import path from "node:path";
import { S3Client, HeadObjectCommand, PutObjectCommand } from "@aws-sdk/client-s3";
import dotenv from "dotenv";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });
dotenv.config({ path: path.resolve(process.cwd(), ".env") });

function parseArg(name, fallback = "") {
  const key = `--${name}=`;
  const matched = process.argv.find((arg) => arg.startsWith(key));
  return matched ? matched.slice(key.length) : fallback;
}

function hasFlag(name) {
  return process.argv.includes(`--${name}`);
}

function printHelp() {
  console.log(`Usage: node scripts/media_transfer_images_to_r2.mjs [options]\n\nOptions:\n  --manifestPath=<path>  Input manifest generated by import or local-stage script\n  --concurrency=<n>      Parallel uploads (default: 4)\n  --dryRun               Do not upload; print planned operations\n  --skipExisting         Skip upload when key already exists in bucket\n  --preferLocal          Prefer localPath in manifest entry when available\n  --localOnly            Require localPath and upload only from local staged files\n  --help                 Show this help\n`);
}

function normalizePublicBase(url) {
  const raw = String(url || "").trim();
  return raw.replace(/\/+$/, "");
}

function detectContentType(url) {
  const lower = String(url || "").toLowerCase();
  if (lower.endsWith(".png")) return "image/png";
  if (lower.endsWith(".webp")) return "image/webp";
  if (lower.endsWith(".gif")) return "image/gif";
  if (lower.endsWith(".avif")) return "image/avif";
  return "image/jpeg";
}

function detectContentTypeFromKeyAndUrl(key, url) {
  const lowerKey = String(key || "").toLowerCase();
  if (lowerKey.endsWith(".png")) return "image/png";
  if (lowerKey.endsWith(".webp")) return "image/webp";
  if (lowerKey.endsWith(".gif")) return "image/gif";
  if (lowerKey.endsWith(".avif")) return "image/avif";
  if (lowerKey.endsWith(".jpg") || lowerKey.endsWith(".jpeg")) return "image/jpeg";
  return detectContentType(url);
}

async function readJsonFile(filePath) {
  const full = path.resolve(filePath);
  const raw = await fs.readFile(full, "utf-8");
  return JSON.parse(raw);
}

async function fetchBinary(url) {
  const response = await fetch(url, {
    headers: {
      Accept: "image/*,application/octet-stream;q=0.8,*/*;q=0.5",
    },
  });
  if (!response.ok) {
    const text = await response.text();
    throw new Error(`download failed ${response.status} ${url} ${text.slice(0, 200)}`);
  }
  const arrayBuffer = await response.arrayBuffer();
  return Buffer.from(arrayBuffer);
}

async function readLocalBinary(localPath) {
  return fs.readFile(path.resolve(localPath));
}

async function localFileExists(localPath) {
  try {
    await fs.access(path.resolve(localPath));
    return true;
  } catch {
    return false;
  }
}

function getR2Config() {
  const endpointRaw = String(process.env.R2_ENDPOINT || "").trim();
  const endpointAccountId = endpointRaw
    ? (() => {
        try {
          const u = new URL(endpointRaw);
          return String(u.hostname || "").split(".")[0] || "";
        } catch {
          return "";
        }
      })()
    : "";
  const accountId = process.env.R2_ACCOUNT_ID || endpointAccountId || "";
  const accessKey = process.env.R2_ACCESS_KEY_ID || process.env.R2_ACCESS_KEY || "";
  const secretKey = process.env.R2_SECRET_ACCESS_KEY || process.env.R2_SECRET_KEY || "";
  const bucket = process.env.R2_BUCKET_NAME || process.env.R2_BUCKET || "kidsmobi";
  const publicBase = normalizePublicBase(process.env.R2_PUBLIC_URL || "");
  if (!accountId || !accessKey || !secretKey || !bucket) {
    throw new Error("Missing R2 credentials. Required: R2_ACCOUNT_ID, R2_ACCESS_KEY_ID(or R2_ACCESS_KEY), R2_SECRET_ACCESS_KEY(or R2_SECRET_KEY), R2_BUCKET_NAME");
  }
  return { accountId, accessKey, secretKey, bucket, publicBase };
}

function createR2Client(config) {
  return new S3Client({
    region: "auto",
    endpoint: `https://${config.accountId}.r2.cloudflarestorage.com`,
    credentials: {
      accessKeyId: config.accessKey,
      secretAccessKey: config.secretKey,
    },
    forcePathStyle: true,
  });
}

async function objectExists(client, bucket, key) {
  try {
    await client.send(
      new HeadObjectCommand({
        Bucket: bucket,
        Key: key,
      })
    );
    return true;
  } catch {
    return false;
  }
}

function limitConcurrency(limit) {
  let active = 0;
  const queue = [];

  const next = () => {
    active -= 1;
    const job = queue.shift();
    if (job) job();
  };

  return async function run(task) {
    if (active >= limit) {
      await new Promise((resolve) => queue.push(resolve));
    }
    active += 1;
    try {
      return await task();
    } finally {
      next();
    }
  };
}

async function main() {
  if (hasFlag("help")) {
    printHelp();
    return;
  }

  const manifestPath = parseArg("manifestPath", process.env.IMAGE_MANIFEST_PATH || "./tmp/front_image_transfer_manifest.json");
  const concurrency = Math.max(1, Number(parseArg("concurrency", "4")) || 4);
  const dryRun = hasFlag("dryRun");
  const skipExisting = hasFlag("skipExisting");
  const preferLocal = hasFlag("preferLocal");
  const localOnly = hasFlag("localOnly");

  const manifest = await readJsonFile(manifestPath);
  const entries = Array.isArray(manifest?.entries) ? manifest.entries : [];
  if (entries.length === 0) {
    throw new Error(`No entries found in manifest: ${manifestPath}`);
  }

  const config = getR2Config();
  const client = createR2Client(config);
  const run = limitConcurrency(concurrency);

  console.log(`[transfer] manifest=${manifestPath}`);
  console.log(`[transfer] entries=${entries.length}`);
  console.log(`[transfer] bucket=${config.bucket}`);
  console.log(`[transfer] dryRun=${dryRun ? "true" : "false"}`);
  console.log(`[transfer] skipExisting=${skipExisting ? "true" : "false"}`);
  console.log(`[transfer] preferLocal=${preferLocal ? "true" : "false"}`);
  console.log(`[transfer] localOnly=${localOnly ? "true" : "false"}`);

  const result = {
    total: entries.length,
    uploaded: 0,
    skipped: 0,
    failed: 0,
    outputs: [],
  };

  await Promise.all(
    entries.map((entry, index) =>
      run(async () => {
        const sourceUrl = String(entry?.sourceUrl || "").trim();
        const key = String(entry?.targetPath || "").replace(/^\/+/, "");
        const localPath = String(entry?.localPath || "").trim();
        if (!key || (!sourceUrl && !localPath)) {
          result.failed += 1;
          return;
        }

        try {
          if (skipExisting) {
            const exists = await objectExists(client, config.bucket, key);
            if (exists) {
              result.skipped += 1;
              result.outputs.push({ index, key, sourceUrl, localPath, status: "skipped-exists" });
              return;
            }
          }

          if (dryRun) {
            result.skipped += 1;
            result.outputs.push({ index, key, sourceUrl, localPath, status: "dry-run" });
            return;
          }

          let body = null;
          let uploadFrom = "remote";
          if (localPath && (preferLocal || localOnly) && (await localFileExists(localPath))) {
            body = await readLocalBinary(localPath);
            uploadFrom = "local";
          } else if (localOnly) {
            throw new Error(`localOnly enabled but local file missing: ${localPath || "<empty>"}`);
          } else {
            body = await fetchBinary(sourceUrl);
          }

          await client.send(
            new PutObjectCommand({
              Bucket: config.bucket,
              Key: key,
              Body: body,
              ContentType: detectContentTypeFromKeyAndUrl(key, sourceUrl),
            })
          );

          result.uploaded += 1;
          result.outputs.push({
            index,
            key,
            sourceUrl,
            localPath,
            uploadFrom,
            status: "uploaded",
            publicUrl: config.publicBase ? `${config.publicBase}/${key}` : "",
          });
        } catch (err) {
          result.failed += 1;
          result.outputs.push({
            index,
            key,
            sourceUrl,
            localPath,
            status: "failed",
            error: String(err?.message || err),
          });
        }
      })
    )
  );

  const reportPath = path.resolve("./tmp/front_image_transfer_report.json");
  await fs.mkdir(path.dirname(reportPath), { recursive: true });
  await fs.writeFile(
    reportPath,
    `${JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        manifestPath: path.resolve(manifestPath),
        importBatchId: manifest?.importBatchId || "",
        ...result,
      },
      null,
      2
    )}\n`,
    "utf-8"
  );

  console.log("[transfer] completed");
  console.log(JSON.stringify({ ...result, reportPath }, null, 2));
}

main().catch((error) => {
  console.error("[transfer] failed", error);
  process.exit(1);
});
